services:
  mongodb_chat_pro:
    image: mongo:latest # 使用最新版本的 MongoDB 镜像
    container_name: mongodb_chat_pro
    restart: always
    ports:
      - '27019:27017' # 将主机的 27017 端口映射到容器的 27017 端口
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # 设置 MongoDB 管理员用户名
      MONGO_INITDB_ROOT_PASSWORD: example # 设置 MongoDB 管理员密码
    volumes:
      - ./mongo_data:/data/db # 持久化存储 MongoDB 数据

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '3200:3000' # 映射后端服务的端口
    volumes:
      - ./backend:/usr/src/app # 挂载本地代码以便开发时使用
    env_file:
      - ./backend/.env # 指定 .env 文件
    depends_on:
      - mongodb_chat_pro # 确保 MongoDB 在启动时先启动

  client:
    image: nginx:alpine
    container_name: client
    ports:
      - '5173:5173' # 将主机的 3000 端口映射到客户端 NGINX 的 5173 端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # 挂载客户端配置文件
      - ./client/dist:/usr/share/nginx/html # 挂载前端构建的静态文件
