services:
  mongodb_chat:
    image: mongo:latest # 使用最新版本的 MongoDB 镜像
    container_name: mongodb_chat
    restart: always
    ports:
      - '27018:27017' # 将主机的 27017 端口映射到容器的 27017 端口
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # 设置 MongoDB 管理员用户名
      MONGO_INITDB_ROOT_PASSWORD: example # 设置 MongoDB 管理员密码
    volumes:
      - ./mongo_data:/data/db # 持久化存储 MongoDB 数据

volumes:
  mongo_data:
    driver: local # 使用本地卷来持久化 MongoDB 数据
    driver_opts:
      o: bind
      type: none
      device: ./mongo_data # 指定主机上的 ./mongo_data 目录
